name: Unit Tests

on: [push]

jobs:
  docker-unit-tests:
    name: Build and run unit tests Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t unit-tests-image -f Dockerfile .

      - name: Run Docker image
        run: docker run --rm unit-tests-image